#!/usr/bin/env python3
"""Build private copyright registration packages for Nayovi Originals.

The script prepares deposits, evidence bundles, hashes, and filing drafts. It
does not submit applications, pay government fees, or certify legal statements.
"""

from __future__ import annotations

import argparse
import datetime as dt
import hashlib
import html
import json
import pathlib
import re
import shutil
import subprocess
import zipfile
from typing import Any


DEFAULT_CONTEXT_ROOT = pathlib.Path('docs/manhwa/context')
DEFAULT_GENERATED_ROOT = pathlib.Path('docs/manhwa/generated')
DEFAULT_OUTPUT_ROOT = pathlib.Path('docs/manhwa/copyright')
DEFAULT_PRIVATE_ROOT = pathlib.Path('docs/manhwa/private')

OFFICIAL_SOURCES = [
  {
    'title': 'U.S. Copyright Office registration portal',
    'url': 'https://www.copyright.gov/registration/',
  },
  {
    'title': 'U.S. Copyright Office AI initiative',
    'url': 'https://www.copyright.gov/ai/',
  },
  {
    'title': 'Copyright Registration Guidance: Works Containing Material Generated by Artificial Intelligence',
    'url': 'https://www.copyright.gov/ai/ai_policy_guidance.pdf',
  },
  {
    'title': 'Group Registration of Unpublished Works',
    'url': 'https://www.copyright.gov/gruw/',
  },
]


def parse_args() -> argparse.Namespace:
  parser = argparse.ArgumentParser(
    description='Prepare a private copyright package for a Nayovi manhwa.'
  )
  parser.add_argument('--series-slug', required=True)
  parser.add_argument('--chapter-number', type=int, default=0)
  parser.add_argument(
    '--scope',
    choices=['auto', 'series', 'chapter'],
    default='auto',
    help='auto uses chapter scope when --chapter-number is provided.',
  )
  parser.add_argument('--package-file', default='')
  parser.add_argument('--context-root', default=str(DEFAULT_CONTEXT_ROOT))
  parser.add_argument('--generated-root', default=str(DEFAULT_GENERATED_ROOT))
  parser.add_argument('--output-root', default=str(DEFAULT_OUTPUT_ROOT))
  parser.add_argument('--private-root', default=str(DEFAULT_PRIVATE_ROOT))
  parser.add_argument(
    '--allow-incomplete',
    action='store_true',
    help='Create the package even when chapter panels are missing. Filing remains blocked.',
  )
  parser.add_argument(
    '--no-queue',
    action='store_true',
    help='Do not append the generated package to the private admin action queue.',
  )
  parser.add_argument(
    '--paid-filing-intent',
    action='store_true',
    help='Mark the draft as intended for official paid filing. Default is free evidence only.',
  )
  return parser.parse_args()


def coerce_dict(value: Any) -> dict[str, Any]:
  return value if isinstance(value, dict) else {}


def coerce_list(value: Any) -> list[Any]:
  return value if isinstance(value, list) else []


def read_json(path: pathlib.Path) -> dict[str, Any]:
  value = json.loads(path.read_text(encoding='utf-8'))
  if not isinstance(value, dict):
    raise ValueError(f'{path}: expected a JSON object')
  return value


def write_json(path: pathlib.Path, value: dict[str, Any]) -> None:
  path.parent.mkdir(parents=True, exist_ok=True)
  path.write_text(json.dumps(value, ensure_ascii=False, indent=2) + '\n', encoding='utf-8')


def utc_now() -> dt.datetime:
  return dt.datetime.now(dt.UTC)


def timestamp_token(now: dt.datetime) -> str:
  return now.strftime('%Y%m%dT%H%M%SZ')


def slugify(value: str, fallback: str) -> str:
  slug = re.sub(r'[^a-zA-Z0-9]+', '-', value.lower()).strip('-')
  return slug or fallback


def sha256_file(path: pathlib.Path) -> str:
  digest = hashlib.sha256()
  with path.open('rb') as handle:
    for chunk in iter(lambda: handle.read(1024 * 1024), b''):
      digest.update(chunk)
  return digest.hexdigest()


def git_commit() -> str:
  try:
    return subprocess.check_output(
      ['git', 'rev-parse', 'HEAD'],
      stderr=subprocess.DEVNULL,
      text=True,
    ).strip()
  except (OSError, subprocess.CalledProcessError):
    return 'unknown'


def git_status_short() -> str:
  try:
    return subprocess.check_output(
      ['git', 'status', '--short'],
      stderr=subprocess.DEVNULL,
      text=True,
    ).strip()
  except (OSError, subprocess.CalledProcessError):
    return 'unavailable'


def chapter_package_path(
  *,
  generated_root: pathlib.Path,
  series_slug: str,
  chapter_number: int,
  explicit_path: str,
) -> pathlib.Path:
  if explicit_path:
    return pathlib.Path(explicit_path)
  return generated_root / f'{series_slug}-chapter-{chapter_number:03d}.json'


def image_manifest_path(
  *,
  private_root: pathlib.Path,
  series_slug: str,
  chapter_number: int,
) -> pathlib.Path:
  return (
    private_root
    / series_slug
    / f'chapter-{chapter_number:03d}'
    / f'chapter-{chapter_number:03d}-images.json'
  )


def local_panel_path(
  *,
  private_root: pathlib.Path,
  series_slug: str,
  chapter_number: int,
  panel_number: int,
) -> pathlib.Path:
  return (
    private_root
    / series_slug
    / f'chapter-{chapter_number:03d}'
    / f'panel-{panel_number:03d}.png'
  )


def context_dir(context_root: pathlib.Path, series_slug: str) -> pathlib.Path:
  return context_root / series_slug


def copy_file(source: pathlib.Path, destination: pathlib.Path) -> None:
  if not source.exists() or not source.is_file():
    return
  destination.parent.mkdir(parents=True, exist_ok=True)
  shutil.copy2(source, destination)


def zip_dir(source_dir: pathlib.Path, zip_path: pathlib.Path) -> None:
  zip_path.parent.mkdir(parents=True, exist_ok=True)
  with zipfile.ZipFile(zip_path, 'w', compression=zipfile.ZIP_DEFLATED) as archive:
    for path in sorted(source_dir.rglob('*')):
      if path.is_file():
        archive.write(path, path.relative_to(source_dir))


def collect_hashes(root: pathlib.Path) -> list[dict[str, str]]:
  entries: list[dict[str, str]] = []
  for path in sorted(root.rglob('*')):
    if path.is_file():
      entries.append(
        {
          'sha256': sha256_file(path),
          'path': str(path.relative_to(root)),
          'bytes': str(path.stat().st_size),
        }
      )
  return entries


def write_hash_file(path: pathlib.Path, hashes: list[dict[str, str]]) -> None:
  lines = [f'{entry["sha256"]}  {entry["path"]}' for entry in hashes]
  path.write_text('\n'.join(lines) + '\n', encoding='utf-8')


def safe_text(value: Any) -> str:
  return str(value or '').strip()


def series_from_package(package: dict[str, Any], fallback_slug: str) -> dict[str, Any]:
  series = coerce_dict(package.get('series'))
  if not series:
    series = {'slug': fallback_slug, 'title': fallback_slug.replace('-', ' ').title()}
  return series


def chapter_from_package(package: dict[str, Any], chapter_number: int) -> dict[str, Any]:
  chapter = coerce_dict(package.get('chapter'))
  if not chapter:
    chapter = {'chapter_number': chapter_number, 'title': f'Chapter {chapter_number}'}
  return chapter


def rendered_panel_numbers(manifest: dict[str, Any]) -> set[int]:
  numbers: set[int] = set()
  for item in coerce_list(manifest.get('rendered')):
    panel_number = int(coerce_dict(item).get('panel_number') or 0)
    if panel_number > 0:
      numbers.add(panel_number)
  return numbers


def build_chapter_work_html(
  *,
  package: dict[str, Any],
  series: dict[str, Any],
  chapter: dict[str, Any],
  copied_panels: dict[int, pathlib.Path],
) -> str:
  title = safe_text(series.get('title'))
  chapter_title = safe_text(chapter.get('title'))
  scenario = safe_text(chapter.get('full_text_scenario'))
  panels_html: list[str] = []

  for raw_panel in coerce_list(package.get('panels')):
    panel = coerce_dict(raw_panel)
    panel_number = int(panel.get('panel_number') or 0)
    narration = safe_text(panel.get('narration'))
    dialogue = [safe_text(line) for line in coerce_list(panel.get('dialogue')) if safe_text(line)]
    image_path = copied_panels.get(panel_number)
    image_html = ''
    if image_path:
      image_html = (
        f'<img src="{html.escape(str(image_path))}" alt="Panel {panel_number}" />'
      )
    dialogue_html = ''.join(f'<li>{html.escape(line)}</li>' for line in dialogue)
    panels_html.append(
      '\n'.join(
        [
          '<section class="panel">',
          f'<h2>Panel {panel_number}</h2>',
          image_html,
          f'<p><strong>Narration:</strong> {html.escape(narration)}</p>' if narration else '',
          f'<ul>{dialogue_html}</ul>' if dialogue_html else '',
          '</section>',
        ]
      )
    )

  return '\n'.join(
    [
      '<!doctype html>',
      '<html lang="en">',
      '<head>',
      '<meta charset="utf-8" />',
      f'<title>{html.escape(title)} - {html.escape(chapter_title)}</title>',
      '<style>',
      'body{margin:0;background:#0b0b10;color:#f7f2ea;font-family:Georgia,serif;}',
      'main{max-width:960px;margin:0 auto;padding:32px 18px;}',
      'img{display:block;width:100%;height:auto;margin:18px 0;border:1px solid #2d2935;}',
      '.panel{margin:0 0 42px;}',
      'p,li{font-size:18px;line-height:1.65;}',
      '</style>',
      '</head>',
      '<body><main>',
      f'<h1>{html.escape(title)}</h1>',
      f'<h2>Chapter {html.escape(str(chapter.get("chapter_number") or ""))}: {html.escape(chapter_title)}</h2>',
      f'<p>{html.escape(scenario)}</p>' if scenario else '',
      *panels_html,
      '</main></body></html>',
    ]
  )


def build_series_work_html(
  *,
  series_bible: dict[str, Any],
  characters: dict[str, Any],
  series_slug: str,
) -> str:
  title = safe_text(series_bible.get('title')) or series_slug.replace('-', ' ').title()
  premise = safe_text(series_bible.get('full_premise'))
  logline = safe_text(series_bible.get('logline'))
  character_items: list[str] = []

  for raw_character in coerce_list(characters.get('characters')):
    character = coerce_dict(raw_character)
    character_items.append(
      '<li>'
      f'<strong>{html.escape(safe_text(character.get("name")) or safe_text(character.get("id")))}</strong>: '
      f'{html.escape(safe_text(character.get("role")))}'
      '</li>'
    )

  return '\n'.join(
    [
      '<!doctype html>',
      '<html lang="en">',
      '<head><meta charset="utf-8" />',
      f'<title>{html.escape(title)} - Series Bible</title>',
      '<style>body{max-width:900px;margin:0 auto;padding:40px 20px;font-family:Georgia,serif;line-height:1.65;}</style>',
      '</head><body>',
      f'<h1>{html.escape(title)}</h1>',
      f'<p><strong>Logline:</strong> {html.escape(logline)}</p>' if logline else '',
      f'<p>{html.escape(premise)}</p>' if premise else '',
      '<h2>Character Register</h2>',
      f'<ul>{"".join(character_items)}</ul>' if character_items else '<p>No character register found.</p>',
      '</body></html>',
    ]
  )


def filing_draft_common(
  *,
  scope: str,
  title: str,
  complete: bool,
  reasons_not_ready: list[str],
  paid_filing_intent: bool,
) -> dict[str, Any]:
  return {
    'generated_for_admin_review_only': True,
    'scope': scope,
    'title': title,
    'filing_ready': bool(paid_filing_intent and complete and not reasons_not_ready),
    'free_evidence_mode': not paid_filing_intent,
    'paid_filing_intent': paid_filing_intent,
    'requires_admin_final_submission': True,
    'reasons_not_ready': reasons_not_ready,
    'official_sources': OFFICIAL_SOURCES,
    'copyright_strategy_notes': [
      'Copyright protects the fixed expression included in this package, not the abstract idea or future unwritten chapters.',
      'Default mode is free evidence/provenance. No official paid copyright filing is attempted or required by the cron.',
      'For AI-assisted works, the application should identify human-authored material and disclaim/exclude AI-generated material where required by current U.S. Copyright Office guidance.',
      'Do not certify or submit an official application until an authorized admin reviews the authorship statement, deposit, claim limitation, and publication status.',
      'The automated package is private evidence and filing preparation, not legal advice.',
    ],
    'suggested_claim_fields_to_confirm': {
      'claimant': 'Nayovi / legal owner to confirm',
      'author': 'Human author/editor/producer to confirm',
      'work_made_for_hire': 'Admin/legal owner to confirm',
      'limitation_of_claim': 'Disclaim AI-generated image/text material as required; claim human selection, coordination, arrangement, editing, story bible, and original human contributions that qualify.',
      'rights_and_permissions_contact': 'Nayovi admin contact to confirm',
    },
    'admin_steps': [
      'Review every file in work-deposit.zip.',
      'Keep package-summary.json, hashes.sha256, work-deposit.zip, and evidence.zip private as free proof of provenance.',
      'Use the package for DMCA/platform disputes if somebody republishes the manhwa and claims ownership.',
      'Only if paid filing is later desired: review usco-application-draft.json, choose the correct eCO registration type, upload the deposit, pay the official fee, and certify only if the admin is authorized.',
    ],
  }


def build_chapter_package(args: argparse.Namespace, now: dt.datetime) -> dict[str, Any]:
  series_slug = args.series_slug
  chapter_number = int(args.chapter_number)
  package_path = chapter_package_path(
    generated_root=pathlib.Path(args.generated_root),
    series_slug=series_slug,
    chapter_number=chapter_number,
    explicit_path=args.package_file,
  )
  if not package_path.exists():
    raise SystemExit(f'Chapter package is missing: {package_path}')

  package = read_json(package_path)
  series = series_from_package(package, series_slug)
  chapter = chapter_from_package(package, chapter_number)
  panels = [coerce_dict(panel) for panel in coerce_list(package.get('panels'))]
  planned_numbers = {
    int(panel.get('panel_number') or 0)
    for panel in panels
    if int(panel.get('panel_number') or 0) > 0
  }
  manifest_path = image_manifest_path(
    private_root=pathlib.Path(args.private_root),
    series_slug=series_slug,
    chapter_number=chapter_number,
  )
  manifest = read_json(manifest_path) if manifest_path.exists() else {}
  rendered_numbers = rendered_panel_numbers(manifest)
  existing_numbers: set[int] = set()
  copied_panels: dict[int, pathlib.Path] = {}

  output_dir = (
    pathlib.Path(args.output_root)
    / series_slug
    / f'chapter-{chapter_number:03d}'
    / timestamp_token(now)
  )
  work_dir = output_dir / 'work-deposit'
  evidence_dir = output_dir / 'evidence'
  panel_dir = work_dir / 'panels'

  for panel_number in sorted(planned_numbers):
    source = local_panel_path(
      private_root=pathlib.Path(args.private_root),
      series_slug=series_slug,
      chapter_number=chapter_number,
      panel_number=panel_number,
    )
    if source.exists():
      existing_numbers.add(panel_number)
      destination = panel_dir / source.name
      copy_file(source, destination)
      copied_panels[panel_number] = pathlib.Path('panels') / source.name

  missing_numbers = sorted(planned_numbers - existing_numbers)
  status = safe_text(package.get('publication_status'))
  reasons_not_ready: list[str] = []
  if missing_numbers:
    reasons_not_ready.append(
      f'Missing rendered chapter panels: {", ".join(str(number) for number in missing_numbers)}'
    )
  if status not in {'approved_by_expert_ai', 'published'}:
    reasons_not_ready.append(f'Chapter package status is not approved/published: {status or "missing"}')
  if not panels:
    reasons_not_ready.append('No panel script exists in the chapter package.')
  if reasons_not_ready and not args.allow_incomplete:
    raise SystemExit(
      'Chapter is not complete enough for copyright packaging. '
      'Use --allow-incomplete to create a private evidence snapshot.'
    )

  work_html = build_chapter_work_html(
    package=package,
    series=series,
    chapter=chapter,
    copied_panels=copied_panels,
  )
  work_dir.mkdir(parents=True, exist_ok=True)
  (work_dir / 'work.html').write_text(work_html, encoding='utf-8')
  write_json(
    work_dir / 'metadata.json',
    {
      'series': series,
      'chapter': chapter,
      'series_slug': series_slug,
      'scope': 'chapter',
      'generated_at': now.isoformat().replace('+00:00', 'Z'),
      'source_package': str(package_path),
      'image_manifest': str(manifest_path) if manifest_path.exists() else None,
      'planned_panel_count': len(planned_numbers),
      'rendered_panel_count': len(existing_numbers),
      'missing_panel_numbers': missing_numbers,
      'copyright_notice': 'Copyright ownership and publication status must be confirmed by an authorized Nayovi admin before filing.',
    },
  )

  copy_file(package_path, evidence_dir / 'source' / package_path.name)
  copy_file(manifest_path, evidence_dir / 'source' / manifest_path.name)
  context_path = context_dir(pathlib.Path(args.context_root), series_slug)
  if context_path.exists():
    for source in sorted(context_path.rglob('*.json')):
      copy_file(source, evidence_dir / 'context' / source.relative_to(context_path))

  title = f'{safe_text(series.get("title"))} - Chapter {chapter.get("chapter_number")}: {safe_text(chapter.get("title"))}'
  filing_draft = filing_draft_common(
    scope='chapter',
    title=title,
    complete=not missing_numbers and bool(panels),
    reasons_not_ready=reasons_not_ready,
    paid_filing_intent=bool(args.paid_filing_intent),
  )
  filing_draft.update(
    {
      'chapter_number': chapter_number,
      'publication_status': status,
      'deposit_recommendation': 'Use work-deposit.zip for the chapter deposit after admin review.',
      'internal_evidence_recommendation': 'Keep evidence.zip private for provenance and originality records; do not upload prompt evidence unless legally advised.',
    }
  )
  write_json(output_dir / 'usco-application-draft.json', filing_draft)
  write_checklist(output_dir / 'filing-checklist.md', filing_draft)

  return finalize_package(
    output_dir=output_dir,
    work_dir=work_dir,
    evidence_dir=evidence_dir,
    now=now,
    scope='chapter',
    series_slug=series_slug,
    chapter_number=chapter_number,
    filing_draft=filing_draft,
    source_paths=[package_path, manifest_path],
    append_queue=not args.no_queue,
  )


def build_series_package(args: argparse.Namespace, now: dt.datetime) -> dict[str, Any]:
  series_slug = args.series_slug
  context_path = context_dir(pathlib.Path(args.context_root), series_slug)
  if not context_path.exists():
    raise SystemExit(f'Series context directory is missing: {context_path}')

  series_bible_path = context_path / 'series-bible.json'
  characters_path = context_path / 'characters.json'
  series_bible = read_json(series_bible_path) if series_bible_path.exists() else {}
  characters = read_json(characters_path) if characters_path.exists() else {}
  title = safe_text(series_bible.get('title')) or series_slug.replace('-', ' ').title()
  reasons_not_ready: list[str] = []
  if not series_bible:
    reasons_not_ready.append('Missing series-bible.json.')
  if not coerce_list(characters.get('characters')):
    reasons_not_ready.append('Missing character register.')
  if reasons_not_ready and not args.allow_incomplete:
    raise SystemExit(
      'Series bible is not complete enough for copyright packaging. '
      'Use --allow-incomplete to create a private evidence snapshot.'
    )

  output_dir = pathlib.Path(args.output_root) / series_slug / 'series-bible' / timestamp_token(now)
  work_dir = output_dir / 'work-deposit'
  evidence_dir = output_dir / 'evidence'
  work_dir.mkdir(parents=True, exist_ok=True)
  (work_dir / 'work.html').write_text(
    build_series_work_html(
      series_bible=series_bible,
      characters=characters,
      series_slug=series_slug,
    ),
    encoding='utf-8',
  )
  write_json(
    work_dir / 'metadata.json',
    {
      'series_slug': series_slug,
      'scope': 'series-bible',
      'title': title,
      'generated_at': now.isoformat().replace('+00:00', 'Z'),
      'source_context': str(context_path),
      'coverage_warning': 'This package covers only the fixed series bible/context expression included here, not future unwritten chapters.',
    },
  )

  for source in sorted(context_path.rglob('*.json')):
    copy_file(source, evidence_dir / 'context' / source.relative_to(context_path))

  filing_draft = filing_draft_common(
    scope='series-bible',
    title=f'{title} - Series Bible',
    complete=not reasons_not_ready,
    reasons_not_ready=reasons_not_ready,
    paid_filing_intent=bool(args.paid_filing_intent),
  )
  filing_draft.update(
    {
      'publication_status': 'unpublished_internal_series_bible',
      'deposit_recommendation': 'Use work-deposit.zip only if registering the fixed story bible/treatment. Register chapters separately when their art/dialogue is complete.',
      'internal_evidence_recommendation': 'Keep evidence.zip private for provenance and originality records.',
    }
  )
  write_json(output_dir / 'usco-application-draft.json', filing_draft)
  write_checklist(output_dir / 'filing-checklist.md', filing_draft)

  return finalize_package(
    output_dir=output_dir,
    work_dir=work_dir,
    evidence_dir=evidence_dir,
    now=now,
    scope='series-bible',
    series_slug=series_slug,
    chapter_number=0,
    filing_draft=filing_draft,
    source_paths=[series_bible_path, characters_path],
    append_queue=not args.no_queue,
  )


def write_checklist(path: pathlib.Path, filing_draft: dict[str, Any]) -> None:
  lines = [
    '# Copyright Filing Checklist',
    '',
    f'- Scope: {filing_draft["scope"]}',
    f'- Title: {filing_draft["title"]}',
    f'- Filing ready by automation checks: {str(filing_draft["filing_ready"]).lower()}',
    f'- Free evidence mode: {str(filing_draft.get("free_evidence_mode", True)).lower()}',
    '- Requires admin final submission: true',
    '',
    '## Blocking Reasons',
  ]
  reasons = coerce_list(filing_draft.get('reasons_not_ready'))
  lines.extend(f'- {reason}' for reason in reasons) if reasons else lines.append('- None.')
  lines.extend(
    [
      '',
      '## Admin Steps',
      *[f'- {step}' for step in coerce_list(filing_draft.get('admin_steps'))],
      '',
      '## Official Sources To Review',
      *[f'- {source["title"]}: {source["url"]}' for source in OFFICIAL_SOURCES],
      '',
      '## Legal Boundary',
      'This automated package prepares evidence and a draft only. It does not submit, pay, or certify a U.S. Copyright Office application.',
      '',
    ]
  )
  path.write_text('\n'.join(lines), encoding='utf-8')


def finalize_package(
  *,
  output_dir: pathlib.Path,
  work_dir: pathlib.Path,
  evidence_dir: pathlib.Path,
  now: dt.datetime,
  scope: str,
  series_slug: str,
  chapter_number: int,
  filing_draft: dict[str, Any],
  source_paths: list[pathlib.Path],
  append_queue: bool,
) -> dict[str, Any]:
  evidence_dir.mkdir(parents=True, exist_ok=True)
  content_hashes = collect_hashes(work_dir) + collect_hashes(evidence_dir)
  write_hash_file(evidence_dir / 'hashes.sha256', content_hashes)

  evidence_manifest = {
    'generated_at': now.isoformat().replace('+00:00', 'Z'),
    'git_commit': git_commit(),
    'git_status_short': git_status_short(),
    'scope': scope,
    'series_slug': series_slug,
    'chapter_number': chapter_number or None,
    'source_paths': [str(path) for path in source_paths if path.exists()],
    'content_hash_count': len(content_hashes),
    'official_sources': OFFICIAL_SOURCES,
  }
  write_json(evidence_dir / 'evidence-manifest.json', evidence_manifest)

  work_zip = output_dir / 'work-deposit.zip'
  evidence_zip = output_dir / 'evidence.zip'
  zip_dir(work_dir, work_zip)
  zip_dir(evidence_dir, evidence_zip)

  summary = {
    'generated_at': now.isoformat().replace('+00:00', 'Z'),
    'scope': scope,
    'series_slug': series_slug,
    'chapter_number': chapter_number or None,
    'output_dir': str(output_dir),
    'filing_ready': bool(filing_draft.get('filing_ready')),
    'requires_admin_final_submission': True,
    'work_deposit_zip': str(work_zip),
    'work_deposit_sha256': sha256_file(work_zip),
    'evidence_zip': str(evidence_zip),
    'evidence_sha256': sha256_file(evidence_zip),
    'usco_application_draft': str(output_dir / 'usco-application-draft.json'),
    'filing_checklist': str(output_dir / 'filing-checklist.md'),
    'legal_boundary': 'Automated preparation only; official filing requires authorized admin review, payment, and certification.',
  }
  write_json(output_dir / 'package-summary.json', summary)

  if append_queue:
    queue_path = output_dir.parents[2] / 'copyright-action-queue.jsonl'
    queue_path.parent.mkdir(parents=True, exist_ok=True)
    with queue_path.open('a', encoding='utf-8') as handle:
      handle.write(json.dumps(summary, ensure_ascii=False) + '\n')

  return summary


def main() -> int:
  args = parse_args()
  scope = args.scope
  if scope == 'auto':
    scope = 'chapter' if int(args.chapter_number) > 0 else 'series'
  if scope == 'chapter' and int(args.chapter_number) <= 0:
    raise SystemExit('--chapter-number is required when scope=chapter')

  now = utc_now()
  if scope == 'chapter':
    summary = build_chapter_package(args, now)
  else:
    summary = build_series_package(args, now)

  print(json.dumps(summary, ensure_ascii=False, indent=2))
  return 0


if __name__ == '__main__':
  raise SystemExit(main())
