/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SupportRouteImport } from './routes/support'
import { Route as PricingRouteImport } from './routes/pricing'
import { Route as LogoutRouteImport } from './routes/logout'
import { Route as HowItWorksRouteImport } from './routes/how-it-works'
import { Route as DownloadRouteImport } from './routes/download'
import { Route as ManagerRouteRouteImport } from './routes/manager/route'
import { Route as LoginRouteRouteImport } from './routes/login/route'
import { Route as AppRouteRouteImport } from './routes/app/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ManagerIndexRouteImport } from './routes/manager/index'
import { Route as LoginIndexRouteImport } from './routes/login/index'
import { Route as AppIndexRouteImport } from './routes/app/index'
import { Route as LegalTermsRouteImport } from './routes/legal/terms'
import { Route as LegalPrivacyRouteImport } from './routes/legal/privacy'
import { Route as CheckoutSuccessRouteImport } from './routes/checkout/success'
import { Route as CheckoutCancelRouteImport } from './routes/checkout/cancel'
import { Route as CheckoutTokenPackKeyRouteImport } from './routes/checkout/$tokenPackKey'
import { Route as ApiUploadRouteImport } from './routes/api/upload'
import { Route as ApiContactRouteImport } from './routes/api/contact'
import { Route as ManagerUsersIndexRouteImport } from './routes/manager/users/index'
import { Route as ManagerProvidersIndexRouteImport } from './routes/manager/providers/index'
import { Route as ManagerLicensesIndexRouteImport } from './routes/manager/licenses/index'
import { Route as ManagerJobsIndexRouteImport } from './routes/manager/jobs/index'
import { Route as ManagerDashboardIndexRouteImport } from './routes/manager/dashboard.index'
import { Route as ManagerContactsIndexRouteImport } from './routes/manager/contacts/index'
import { Route as ManagerChaptersIndexRouteImport } from './routes/manager/chapters/index'
import { Route as ManagerAccountIndexRouteImport } from './routes/manager/account.index'
import { Route as LoginVerifyIndexRouteImport } from './routes/login/verify.index'
import { Route as LoginErrorIndexRouteImport } from './routes/login/error.index'
import { Route as AppAccountIndexRouteImport } from './routes/app/account.index'
import { Route as ApiRpcSplatRouteImport } from './routes/api/rpc.$'
import { Route as ApiRestSplatRouteImport } from './routes/api/rest.$'
import { Route as ApiPaymentsWebhookRouteImport } from './routes/api/payments/webhook'
import { Route as ApiPaymentsCheckoutRouteImport } from './routes/api/payments/checkout'
import { Route as ApiOpenapiAuthRouteImport } from './routes/api/openapi/auth'
import { Route as ApiOpenapiAppRouteImport } from './routes/api/openapi/app'
import { Route as ApiMobileJobsRouteImport } from './routes/api/mobile/jobs'
import { Route as ApiMobileHeartbeatRouteImport } from './routes/api/mobile/heartbeat'
import { Route as ApiDownloadApkRouteImport } from './routes/api/download/apk'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth.$'
import { Route as ApiActivationRedeemRouteImport } from './routes/api/activation/redeem'
import { Route as ManagerUsersNewIndexRouteImport } from './routes/manager/users/new.index'
import { Route as ManagerUsersIdIndexRouteImport } from './routes/manager/users/$id.index'
import { Route as ManagerLicensesKeyIndexRouteImport } from './routes/manager/licenses/$key.index'
import { Route as ManagerJobsIdIndexRouteImport } from './routes/manager/jobs/$id.index'
import { Route as ManagerDevicesIdIndexRouteImport } from './routes/manager/devices/$id.index'
import { Route as ManagerContactsIdIndexRouteImport } from './routes/manager/contacts/$id.index'
import { Route as ManagerChaptersCacheKeyIndexRouteImport } from './routes/manager/chapters/$cacheKey.index'
import { Route as ApiOpenapiAuthSchemaRouteImport } from './routes/api/openapi/auth.schema'
import { Route as ApiOpenapiAppSchemaRouteImport } from './routes/api/openapi/app.schema'
import { Route as ApiMobileSubscriptionCancelRouteImport } from './routes/api/mobile/subscription/cancel'
import { Route as ApiMobileSourceDiscoveryVerifyRouteImport } from './routes/api/mobile/source-discovery/verify'
import { Route as ApiMobileSourceDiscoveryPlanRouteImport } from './routes/api/mobile/source-discovery/plan'
import { Route as ApiMobileSourceDiscoveryMethodFeedbackRouteImport } from './routes/api/mobile/source-discovery/method-feedback'
import { Route as ApiMobileMangaPageTranslateRouteImport } from './routes/api/mobile/manga-page/translate'
import { Route as ApiMobileAuthSessionRouteImport } from './routes/api/mobile/auth/session'
import { Route as ApiMobileAuthRefreshRouteImport } from './routes/api/mobile/auth/refresh'
import { Route as ApiMobileAuthActivateRouteImport } from './routes/api/mobile/auth/activate'
import { Route as ApiDevEmailTemplateRouteImport } from './routes/api/dev.email.$template'
import { Route as ManagerUsersIdUpdateIndexRouteImport } from './routes/manager/users/$id.update.index'
import { Route as ApiMobileJobsJobIdIndexRouteImport } from './routes/api/mobile/jobs/$jobId.index'
import { Route as ApiMobileJobsJobIdResultRouteImport } from './routes/api/mobile/jobs/$jobId/result'
import { Route as ApiMobileJobsJobIdCompleteRouteImport } from './routes/api/mobile/jobs/$jobId/complete'
import { Route as ApiMobileJobsJobIdPagesPageNumberRouteImport } from './routes/api/mobile/jobs/$jobId/pages/$pageNumber'

const SupportRoute = SupportRouteImport.update({
  id: '/support',
  path: '/support',
  getParentRoute: () => rootRouteImport,
} as any)
const PricingRoute = PricingRouteImport.update({
  id: '/pricing',
  path: '/pricing',
  getParentRoute: () => rootRouteImport,
} as any)
const LogoutRoute = LogoutRouteImport.update({
  id: '/logout',
  path: '/logout',
  getParentRoute: () => rootRouteImport,
} as any)
const HowItWorksRoute = HowItWorksRouteImport.update({
  id: '/how-it-works',
  path: '/how-it-works',
  getParentRoute: () => rootRouteImport,
} as any)
const DownloadRoute = DownloadRouteImport.update({
  id: '/download',
  path: '/download',
  getParentRoute: () => rootRouteImport,
} as any)
const ManagerRouteRoute = ManagerRouteRouteImport.update({
  id: '/manager',
  path: '/manager',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRouteRoute = LoginRouteRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRouteRoute = AppRouteRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ManagerIndexRoute = ManagerIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ManagerRouteRoute,
} as any)
const LoginIndexRoute = LoginIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => LoginRouteRoute,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRouteRoute,
} as any)
const LegalTermsRoute = LegalTermsRouteImport.update({
  id: '/legal/terms',
  path: '/legal/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const LegalPrivacyRoute = LegalPrivacyRouteImport.update({
  id: '/legal/privacy',
  path: '/legal/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckoutSuccessRoute = CheckoutSuccessRouteImport.update({
  id: '/checkout/success',
  path: '/checkout/success',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckoutCancelRoute = CheckoutCancelRouteImport.update({
  id: '/checkout/cancel',
  path: '/checkout/cancel',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckoutTokenPackKeyRoute = CheckoutTokenPackKeyRouteImport.update({
  id: '/checkout/$tokenPackKey',
  path: '/checkout/$tokenPackKey',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiUploadRoute = ApiUploadRouteImport.update({
  id: '/api/upload',
  path: '/api/upload',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiContactRoute = ApiContactRouteImport.update({
  id: '/api/contact',
  path: '/api/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const ManagerUsersIndexRoute = ManagerUsersIndexRouteImport.update({
  id: '/users/',
  path: '/users/',
  getParentRoute: () => ManagerRouteRoute,
} as any)
const ManagerProvidersIndexRoute = ManagerProvidersIndexRouteImport.update({
  id: '/providers/',
  path: '/providers/',
  getParentRoute: () => ManagerRouteRoute,
} as any)
const ManagerLicensesIndexRoute = ManagerLicensesIndexRouteImport.update({
  id: '/licenses/',
  path: '/licenses/',
  getParentRoute: () => ManagerRouteRoute,
} as any)
const ManagerJobsIndexRoute = ManagerJobsIndexRouteImport.update({
  id: '/jobs/',
  path: '/jobs/',
  getParentRoute: () => ManagerRouteRoute,
} as any)
const ManagerDashboardIndexRoute = ManagerDashboardIndexRouteImport.update({
  id: '/dashboard/',
  path: '/dashboard/',
  getParentRoute: () => ManagerRouteRoute,
} as any)
const ManagerContactsIndexRoute = ManagerContactsIndexRouteImport.update({
  id: '/contacts/',
  path: '/contacts/',
  getParentRoute: () => ManagerRouteRoute,
} as any)
const ManagerChaptersIndexRoute = ManagerChaptersIndexRouteImport.update({
  id: '/chapters/',
  path: '/chapters/',
  getParentRoute: () => ManagerRouteRoute,
} as any)
const ManagerAccountIndexRoute = ManagerAccountIndexRouteImport.update({
  id: '/account/',
  path: '/account/',
  getParentRoute: () => ManagerRouteRoute,
} as any)
const LoginVerifyIndexRoute = LoginVerifyIndexRouteImport.update({
  id: '/verify/',
  path: '/verify/',
  getParentRoute: () => LoginRouteRoute,
} as any)
const LoginErrorIndexRoute = LoginErrorIndexRouteImport.update({
  id: '/error/',
  path: '/error/',
  getParentRoute: () => LoginRouteRoute,
} as any)
const AppAccountIndexRoute = AppAccountIndexRouteImport.update({
  id: '/account/',
  path: '/account/',
  getParentRoute: () => AppRouteRoute,
} as any)
const ApiRpcSplatRoute = ApiRpcSplatRouteImport.update({
  id: '/api/rpc/$',
  path: '/api/rpc/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiRestSplatRoute = ApiRestSplatRouteImport.update({
  id: '/api/rest/$',
  path: '/api/rest/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPaymentsWebhookRoute = ApiPaymentsWebhookRouteImport.update({
  id: '/api/payments/webhook',
  path: '/api/payments/webhook',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPaymentsCheckoutRoute = ApiPaymentsCheckoutRouteImport.update({
  id: '/api/payments/checkout',
  path: '/api/payments/checkout',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiOpenapiAuthRoute = ApiOpenapiAuthRouteImport.update({
  id: '/api/openapi/auth',
  path: '/api/openapi/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiOpenapiAppRoute = ApiOpenapiAppRouteImport.update({
  id: '/api/openapi/app',
  path: '/api/openapi/app',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiMobileJobsRoute = ApiMobileJobsRouteImport.update({
  id: '/api/mobile/jobs',
  path: '/api/mobile/jobs',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiMobileHeartbeatRoute = ApiMobileHeartbeatRouteImport.update({
  id: '/api/mobile/heartbeat',
  path: '/api/mobile/heartbeat',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiDownloadApkRoute = ApiDownloadApkRouteImport.update({
  id: '/api/download/apk',
  path: '/api/download/apk',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiActivationRedeemRoute = ApiActivationRedeemRouteImport.update({
  id: '/api/activation/redeem',
  path: '/api/activation/redeem',
  getParentRoute: () => rootRouteImport,
} as any)
const ManagerUsersNewIndexRoute = ManagerUsersNewIndexRouteImport.update({
  id: '/users/new/',
  path: '/users/new/',
  getParentRoute: () => ManagerRouteRoute,
} as any)
const ManagerUsersIdIndexRoute = ManagerUsersIdIndexRouteImport.update({
  id: '/users/$id/',
  path: '/users/$id/',
  getParentRoute: () => ManagerRouteRoute,
} as any)
const ManagerLicensesKeyIndexRoute = ManagerLicensesKeyIndexRouteImport.update({
  id: '/licenses/$key/',
  path: '/licenses/$key/',
  getParentRoute: () => ManagerRouteRoute,
} as any)
const ManagerJobsIdIndexRoute = ManagerJobsIdIndexRouteImport.update({
  id: '/jobs/$id/',
  path: '/jobs/$id/',
  getParentRoute: () => ManagerRouteRoute,
} as any)
const ManagerDevicesIdIndexRoute = ManagerDevicesIdIndexRouteImport.update({
  id: '/devices/$id/',
  path: '/devices/$id/',
  getParentRoute: () => ManagerRouteRoute,
} as any)
const ManagerContactsIdIndexRoute = ManagerContactsIdIndexRouteImport.update({
  id: '/contacts/$id/',
  path: '/contacts/$id/',
  getParentRoute: () => ManagerRouteRoute,
} as any)
const ManagerChaptersCacheKeyIndexRoute =
  ManagerChaptersCacheKeyIndexRouteImport.update({
    id: '/chapters/$cacheKey/',
    path: '/chapters/$cacheKey/',
    getParentRoute: () => ManagerRouteRoute,
  } as any)
const ApiOpenapiAuthSchemaRoute = ApiOpenapiAuthSchemaRouteImport.update({
  id: '/schema',
  path: '/schema',
  getParentRoute: () => ApiOpenapiAuthRoute,
} as any)
const ApiOpenapiAppSchemaRoute = ApiOpenapiAppSchemaRouteImport.update({
  id: '/schema',
  path: '/schema',
  getParentRoute: () => ApiOpenapiAppRoute,
} as any)
const ApiMobileSubscriptionCancelRoute =
  ApiMobileSubscriptionCancelRouteImport.update({
    id: '/api/mobile/subscription/cancel',
    path: '/api/mobile/subscription/cancel',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiMobileSourceDiscoveryVerifyRoute =
  ApiMobileSourceDiscoveryVerifyRouteImport.update({
    id: '/api/mobile/source-discovery/verify',
    path: '/api/mobile/source-discovery/verify',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiMobileSourceDiscoveryPlanRoute =
  ApiMobileSourceDiscoveryPlanRouteImport.update({
    id: '/api/mobile/source-discovery/plan',
    path: '/api/mobile/source-discovery/plan',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiMobileSourceDiscoveryMethodFeedbackRoute =
  ApiMobileSourceDiscoveryMethodFeedbackRouteImport.update({
    id: '/api/mobile/source-discovery/method-feedback',
    path: '/api/mobile/source-discovery/method-feedback',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiMobileMangaPageTranslateRoute =
  ApiMobileMangaPageTranslateRouteImport.update({
    id: '/api/mobile/manga-page/translate',
    path: '/api/mobile/manga-page/translate',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiMobileAuthSessionRoute = ApiMobileAuthSessionRouteImport.update({
  id: '/api/mobile/auth/session',
  path: '/api/mobile/auth/session',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiMobileAuthRefreshRoute = ApiMobileAuthRefreshRouteImport.update({
  id: '/api/mobile/auth/refresh',
  path: '/api/mobile/auth/refresh',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiMobileAuthActivateRoute = ApiMobileAuthActivateRouteImport.update({
  id: '/api/mobile/auth/activate',
  path: '/api/mobile/auth/activate',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiDevEmailTemplateRoute = ApiDevEmailTemplateRouteImport.update({
  id: '/api/dev/email/$template',
  path: '/api/dev/email/$template',
  getParentRoute: () => rootRouteImport,
} as any)
const ManagerUsersIdUpdateIndexRoute =
  ManagerUsersIdUpdateIndexRouteImport.update({
    id: '/users/$id/update/',
    path: '/users/$id/update/',
    getParentRoute: () => ManagerRouteRoute,
  } as any)
const ApiMobileJobsJobIdIndexRoute = ApiMobileJobsJobIdIndexRouteImport.update({
  id: '/$jobId/',
  path: '/$jobId/',
  getParentRoute: () => ApiMobileJobsRoute,
} as any)
const ApiMobileJobsJobIdResultRoute =
  ApiMobileJobsJobIdResultRouteImport.update({
    id: '/$jobId/result',
    path: '/$jobId/result',
    getParentRoute: () => ApiMobileJobsRoute,
  } as any)
const ApiMobileJobsJobIdCompleteRoute =
  ApiMobileJobsJobIdCompleteRouteImport.update({
    id: '/$jobId/complete',
    path: '/$jobId/complete',
    getParentRoute: () => ApiMobileJobsRoute,
  } as any)
const ApiMobileJobsJobIdPagesPageNumberRoute =
  ApiMobileJobsJobIdPagesPageNumberRouteImport.update({
    id: '/$jobId/pages/$pageNumber',
    path: '/$jobId/pages/$pageNumber',
    getParentRoute: () => ApiMobileJobsRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/app': typeof AppRouteRouteWithChildren
  '/login': typeof LoginRouteRouteWithChildren
  '/manager': typeof ManagerRouteRouteWithChildren
  '/download': typeof DownloadRoute
  '/how-it-works': typeof HowItWorksRoute
  '/logout': typeof LogoutRoute
  '/pricing': typeof PricingRoute
  '/support': typeof SupportRoute
  '/api/contact': typeof ApiContactRoute
  '/api/upload': typeof ApiUploadRoute
  '/checkout/$tokenPackKey': typeof CheckoutTokenPackKeyRoute
  '/checkout/cancel': typeof CheckoutCancelRoute
  '/checkout/success': typeof CheckoutSuccessRoute
  '/legal/privacy': typeof LegalPrivacyRoute
  '/legal/terms': typeof LegalTermsRoute
  '/app/': typeof AppIndexRoute
  '/login/': typeof LoginIndexRoute
  '/manager/': typeof ManagerIndexRoute
  '/api/activation/redeem': typeof ApiActivationRedeemRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/download/apk': typeof ApiDownloadApkRoute
  '/api/mobile/heartbeat': typeof ApiMobileHeartbeatRoute
  '/api/mobile/jobs': typeof ApiMobileJobsRouteWithChildren
  '/api/openapi/app': typeof ApiOpenapiAppRouteWithChildren
  '/api/openapi/auth': typeof ApiOpenapiAuthRouteWithChildren
  '/api/payments/checkout': typeof ApiPaymentsCheckoutRoute
  '/api/payments/webhook': typeof ApiPaymentsWebhookRoute
  '/api/rest/$': typeof ApiRestSplatRoute
  '/api/rpc/$': typeof ApiRpcSplatRoute
  '/app/account/': typeof AppAccountIndexRoute
  '/login/error/': typeof LoginErrorIndexRoute
  '/login/verify/': typeof LoginVerifyIndexRoute
  '/manager/account/': typeof ManagerAccountIndexRoute
  '/manager/chapters/': typeof ManagerChaptersIndexRoute
  '/manager/contacts/': typeof ManagerContactsIndexRoute
  '/manager/dashboard/': typeof ManagerDashboardIndexRoute
  '/manager/jobs/': typeof ManagerJobsIndexRoute
  '/manager/licenses/': typeof ManagerLicensesIndexRoute
  '/manager/providers/': typeof ManagerProvidersIndexRoute
  '/manager/users/': typeof ManagerUsersIndexRoute
  '/api/dev/email/$template': typeof ApiDevEmailTemplateRoute
  '/api/mobile/auth/activate': typeof ApiMobileAuthActivateRoute
  '/api/mobile/auth/refresh': typeof ApiMobileAuthRefreshRoute
  '/api/mobile/auth/session': typeof ApiMobileAuthSessionRoute
  '/api/mobile/manga-page/translate': typeof ApiMobileMangaPageTranslateRoute
  '/api/mobile/source-discovery/method-feedback': typeof ApiMobileSourceDiscoveryMethodFeedbackRoute
  '/api/mobile/source-discovery/plan': typeof ApiMobileSourceDiscoveryPlanRoute
  '/api/mobile/source-discovery/verify': typeof ApiMobileSourceDiscoveryVerifyRoute
  '/api/mobile/subscription/cancel': typeof ApiMobileSubscriptionCancelRoute
  '/api/openapi/app/schema': typeof ApiOpenapiAppSchemaRoute
  '/api/openapi/auth/schema': typeof ApiOpenapiAuthSchemaRoute
  '/manager/chapters/$cacheKey/': typeof ManagerChaptersCacheKeyIndexRoute
  '/manager/contacts/$id/': typeof ManagerContactsIdIndexRoute
  '/manager/devices/$id/': typeof ManagerDevicesIdIndexRoute
  '/manager/jobs/$id/': typeof ManagerJobsIdIndexRoute
  '/manager/licenses/$key/': typeof ManagerLicensesKeyIndexRoute
  '/manager/users/$id/': typeof ManagerUsersIdIndexRoute
  '/manager/users/new/': typeof ManagerUsersNewIndexRoute
  '/api/mobile/jobs/$jobId/complete': typeof ApiMobileJobsJobIdCompleteRoute
  '/api/mobile/jobs/$jobId/result': typeof ApiMobileJobsJobIdResultRoute
  '/api/mobile/jobs/$jobId/': typeof ApiMobileJobsJobIdIndexRoute
  '/manager/users/$id/update/': typeof ManagerUsersIdUpdateIndexRoute
  '/api/mobile/jobs/$jobId/pages/$pageNumber': typeof ApiMobileJobsJobIdPagesPageNumberRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/download': typeof DownloadRoute
  '/how-it-works': typeof HowItWorksRoute
  '/logout': typeof LogoutRoute
  '/pricing': typeof PricingRoute
  '/support': typeof SupportRoute
  '/api/contact': typeof ApiContactRoute
  '/api/upload': typeof ApiUploadRoute
  '/checkout/$tokenPackKey': typeof CheckoutTokenPackKeyRoute
  '/checkout/cancel': typeof CheckoutCancelRoute
  '/checkout/success': typeof CheckoutSuccessRoute
  '/legal/privacy': typeof LegalPrivacyRoute
  '/legal/terms': typeof LegalTermsRoute
  '/app': typeof AppIndexRoute
  '/login': typeof LoginIndexRoute
  '/manager': typeof ManagerIndexRoute
  '/api/activation/redeem': typeof ApiActivationRedeemRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/download/apk': typeof ApiDownloadApkRoute
  '/api/mobile/heartbeat': typeof ApiMobileHeartbeatRoute
  '/api/mobile/jobs': typeof ApiMobileJobsRouteWithChildren
  '/api/openapi/app': typeof ApiOpenapiAppRouteWithChildren
  '/api/openapi/auth': typeof ApiOpenapiAuthRouteWithChildren
  '/api/payments/checkout': typeof ApiPaymentsCheckoutRoute
  '/api/payments/webhook': typeof ApiPaymentsWebhookRoute
  '/api/rest/$': typeof ApiRestSplatRoute
  '/api/rpc/$': typeof ApiRpcSplatRoute
  '/app/account': typeof AppAccountIndexRoute
  '/login/error': typeof LoginErrorIndexRoute
  '/login/verify': typeof LoginVerifyIndexRoute
  '/manager/account': typeof ManagerAccountIndexRoute
  '/manager/chapters': typeof ManagerChaptersIndexRoute
  '/manager/contacts': typeof ManagerContactsIndexRoute
  '/manager/dashboard': typeof ManagerDashboardIndexRoute
  '/manager/jobs': typeof ManagerJobsIndexRoute
  '/manager/licenses': typeof ManagerLicensesIndexRoute
  '/manager/providers': typeof ManagerProvidersIndexRoute
  '/manager/users': typeof ManagerUsersIndexRoute
  '/api/dev/email/$template': typeof ApiDevEmailTemplateRoute
  '/api/mobile/auth/activate': typeof ApiMobileAuthActivateRoute
  '/api/mobile/auth/refresh': typeof ApiMobileAuthRefreshRoute
  '/api/mobile/auth/session': typeof ApiMobileAuthSessionRoute
  '/api/mobile/manga-page/translate': typeof ApiMobileMangaPageTranslateRoute
  '/api/mobile/source-discovery/method-feedback': typeof ApiMobileSourceDiscoveryMethodFeedbackRoute
  '/api/mobile/source-discovery/plan': typeof ApiMobileSourceDiscoveryPlanRoute
  '/api/mobile/source-discovery/verify': typeof ApiMobileSourceDiscoveryVerifyRoute
  '/api/mobile/subscription/cancel': typeof ApiMobileSubscriptionCancelRoute
  '/api/openapi/app/schema': typeof ApiOpenapiAppSchemaRoute
  '/api/openapi/auth/schema': typeof ApiOpenapiAuthSchemaRoute
  '/manager/chapters/$cacheKey': typeof ManagerChaptersCacheKeyIndexRoute
  '/manager/contacts/$id': typeof ManagerContactsIdIndexRoute
  '/manager/devices/$id': typeof ManagerDevicesIdIndexRoute
  '/manager/jobs/$id': typeof ManagerJobsIdIndexRoute
  '/manager/licenses/$key': typeof ManagerLicensesKeyIndexRoute
  '/manager/users/$id': typeof ManagerUsersIdIndexRoute
  '/manager/users/new': typeof ManagerUsersNewIndexRoute
  '/api/mobile/jobs/$jobId/complete': typeof ApiMobileJobsJobIdCompleteRoute
  '/api/mobile/jobs/$jobId/result': typeof ApiMobileJobsJobIdResultRoute
  '/api/mobile/jobs/$jobId': typeof ApiMobileJobsJobIdIndexRoute
  '/manager/users/$id/update': typeof ManagerUsersIdUpdateIndexRoute
  '/api/mobile/jobs/$jobId/pages/$pageNumber': typeof ApiMobileJobsJobIdPagesPageNumberRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/app': typeof AppRouteRouteWithChildren
  '/login': typeof LoginRouteRouteWithChildren
  '/manager': typeof ManagerRouteRouteWithChildren
  '/download': typeof DownloadRoute
  '/how-it-works': typeof HowItWorksRoute
  '/logout': typeof LogoutRoute
  '/pricing': typeof PricingRoute
  '/support': typeof SupportRoute
  '/api/contact': typeof ApiContactRoute
  '/api/upload': typeof ApiUploadRoute
  '/checkout/$tokenPackKey': typeof CheckoutTokenPackKeyRoute
  '/checkout/cancel': typeof CheckoutCancelRoute
  '/checkout/success': typeof CheckoutSuccessRoute
  '/legal/privacy': typeof LegalPrivacyRoute
  '/legal/terms': typeof LegalTermsRoute
  '/app/': typeof AppIndexRoute
  '/login/': typeof LoginIndexRoute
  '/manager/': typeof ManagerIndexRoute
  '/api/activation/redeem': typeof ApiActivationRedeemRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/download/apk': typeof ApiDownloadApkRoute
  '/api/mobile/heartbeat': typeof ApiMobileHeartbeatRoute
  '/api/mobile/jobs': typeof ApiMobileJobsRouteWithChildren
  '/api/openapi/app': typeof ApiOpenapiAppRouteWithChildren
  '/api/openapi/auth': typeof ApiOpenapiAuthRouteWithChildren
  '/api/payments/checkout': typeof ApiPaymentsCheckoutRoute
  '/api/payments/webhook': typeof ApiPaymentsWebhookRoute
  '/api/rest/$': typeof ApiRestSplatRoute
  '/api/rpc/$': typeof ApiRpcSplatRoute
  '/app/account/': typeof AppAccountIndexRoute
  '/login/error/': typeof LoginErrorIndexRoute
  '/login/verify/': typeof LoginVerifyIndexRoute
  '/manager/account/': typeof ManagerAccountIndexRoute
  '/manager/chapters/': typeof ManagerChaptersIndexRoute
  '/manager/contacts/': typeof ManagerContactsIndexRoute
  '/manager/dashboard/': typeof ManagerDashboardIndexRoute
  '/manager/jobs/': typeof ManagerJobsIndexRoute
  '/manager/licenses/': typeof ManagerLicensesIndexRoute
  '/manager/providers/': typeof ManagerProvidersIndexRoute
  '/manager/users/': typeof ManagerUsersIndexRoute
  '/api/dev/email/$template': typeof ApiDevEmailTemplateRoute
  '/api/mobile/auth/activate': typeof ApiMobileAuthActivateRoute
  '/api/mobile/auth/refresh': typeof ApiMobileAuthRefreshRoute
  '/api/mobile/auth/session': typeof ApiMobileAuthSessionRoute
  '/api/mobile/manga-page/translate': typeof ApiMobileMangaPageTranslateRoute
  '/api/mobile/source-discovery/method-feedback': typeof ApiMobileSourceDiscoveryMethodFeedbackRoute
  '/api/mobile/source-discovery/plan': typeof ApiMobileSourceDiscoveryPlanRoute
  '/api/mobile/source-discovery/verify': typeof ApiMobileSourceDiscoveryVerifyRoute
  '/api/mobile/subscription/cancel': typeof ApiMobileSubscriptionCancelRoute
  '/api/openapi/app/schema': typeof ApiOpenapiAppSchemaRoute
  '/api/openapi/auth/schema': typeof ApiOpenapiAuthSchemaRoute
  '/manager/chapters/$cacheKey/': typeof ManagerChaptersCacheKeyIndexRoute
  '/manager/contacts/$id/': typeof ManagerContactsIdIndexRoute
  '/manager/devices/$id/': typeof ManagerDevicesIdIndexRoute
  '/manager/jobs/$id/': typeof ManagerJobsIdIndexRoute
  '/manager/licenses/$key/': typeof ManagerLicensesKeyIndexRoute
  '/manager/users/$id/': typeof ManagerUsersIdIndexRoute
  '/manager/users/new/': typeof ManagerUsersNewIndexRoute
  '/api/mobile/jobs/$jobId/complete': typeof ApiMobileJobsJobIdCompleteRoute
  '/api/mobile/jobs/$jobId/result': typeof ApiMobileJobsJobIdResultRoute
  '/api/mobile/jobs/$jobId/': typeof ApiMobileJobsJobIdIndexRoute
  '/manager/users/$id/update/': typeof ManagerUsersIdUpdateIndexRoute
  '/api/mobile/jobs/$jobId/pages/$pageNumber': typeof ApiMobileJobsJobIdPagesPageNumberRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/app'
    | '/login'
    | '/manager'
    | '/download'
    | '/how-it-works'
    | '/logout'
    | '/pricing'
    | '/support'
    | '/api/contact'
    | '/api/upload'
    | '/checkout/$tokenPackKey'
    | '/checkout/cancel'
    | '/checkout/success'
    | '/legal/privacy'
    | '/legal/terms'
    | '/app/'
    | '/login/'
    | '/manager/'
    | '/api/activation/redeem'
    | '/api/auth/$'
    | '/api/download/apk'
    | '/api/mobile/heartbeat'
    | '/api/mobile/jobs'
    | '/api/openapi/app'
    | '/api/openapi/auth'
    | '/api/payments/checkout'
    | '/api/payments/webhook'
    | '/api/rest/$'
    | '/api/rpc/$'
    | '/app/account/'
    | '/login/error/'
    | '/login/verify/'
    | '/manager/account/'
    | '/manager/chapters/'
    | '/manager/contacts/'
    | '/manager/dashboard/'
    | '/manager/jobs/'
    | '/manager/licenses/'
    | '/manager/providers/'
    | '/manager/users/'
    | '/api/dev/email/$template'
    | '/api/mobile/auth/activate'
    | '/api/mobile/auth/refresh'
    | '/api/mobile/auth/session'
    | '/api/mobile/manga-page/translate'
    | '/api/mobile/source-discovery/method-feedback'
    | '/api/mobile/source-discovery/plan'
    | '/api/mobile/source-discovery/verify'
    | '/api/mobile/subscription/cancel'
    | '/api/openapi/app/schema'
    | '/api/openapi/auth/schema'
    | '/manager/chapters/$cacheKey/'
    | '/manager/contacts/$id/'
    | '/manager/devices/$id/'
    | '/manager/jobs/$id/'
    | '/manager/licenses/$key/'
    | '/manager/users/$id/'
    | '/manager/users/new/'
    | '/api/mobile/jobs/$jobId/complete'
    | '/api/mobile/jobs/$jobId/result'
    | '/api/mobile/jobs/$jobId/'
    | '/manager/users/$id/update/'
    | '/api/mobile/jobs/$jobId/pages/$pageNumber'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/download'
    | '/how-it-works'
    | '/logout'
    | '/pricing'
    | '/support'
    | '/api/contact'
    | '/api/upload'
    | '/checkout/$tokenPackKey'
    | '/checkout/cancel'
    | '/checkout/success'
    | '/legal/privacy'
    | '/legal/terms'
    | '/app'
    | '/login'
    | '/manager'
    | '/api/activation/redeem'
    | '/api/auth/$'
    | '/api/download/apk'
    | '/api/mobile/heartbeat'
    | '/api/mobile/jobs'
    | '/api/openapi/app'
    | '/api/openapi/auth'
    | '/api/payments/checkout'
    | '/api/payments/webhook'
    | '/api/rest/$'
    | '/api/rpc/$'
    | '/app/account'
    | '/login/error'
    | '/login/verify'
    | '/manager/account'
    | '/manager/chapters'
    | '/manager/contacts'
    | '/manager/dashboard'
    | '/manager/jobs'
    | '/manager/licenses'
    | '/manager/providers'
    | '/manager/users'
    | '/api/dev/email/$template'
    | '/api/mobile/auth/activate'
    | '/api/mobile/auth/refresh'
    | '/api/mobile/auth/session'
    | '/api/mobile/manga-page/translate'
    | '/api/mobile/source-discovery/method-feedback'
    | '/api/mobile/source-discovery/plan'
    | '/api/mobile/source-discovery/verify'
    | '/api/mobile/subscription/cancel'
    | '/api/openapi/app/schema'
    | '/api/openapi/auth/schema'
    | '/manager/chapters/$cacheKey'
    | '/manager/contacts/$id'
    | '/manager/devices/$id'
    | '/manager/jobs/$id'
    | '/manager/licenses/$key'
    | '/manager/users/$id'
    | '/manager/users/new'
    | '/api/mobile/jobs/$jobId/complete'
    | '/api/mobile/jobs/$jobId/result'
    | '/api/mobile/jobs/$jobId'
    | '/manager/users/$id/update'
    | '/api/mobile/jobs/$jobId/pages/$pageNumber'
  id:
    | '__root__'
    | '/'
    | '/app'
    | '/login'
    | '/manager'
    | '/download'
    | '/how-it-works'
    | '/logout'
    | '/pricing'
    | '/support'
    | '/api/contact'
    | '/api/upload'
    | '/checkout/$tokenPackKey'
    | '/checkout/cancel'
    | '/checkout/success'
    | '/legal/privacy'
    | '/legal/terms'
    | '/app/'
    | '/login/'
    | '/manager/'
    | '/api/activation/redeem'
    | '/api/auth/$'
    | '/api/download/apk'
    | '/api/mobile/heartbeat'
    | '/api/mobile/jobs'
    | '/api/openapi/app'
    | '/api/openapi/auth'
    | '/api/payments/checkout'
    | '/api/payments/webhook'
    | '/api/rest/$'
    | '/api/rpc/$'
    | '/app/account/'
    | '/login/error/'
    | '/login/verify/'
    | '/manager/account/'
    | '/manager/chapters/'
    | '/manager/contacts/'
    | '/manager/dashboard/'
    | '/manager/jobs/'
    | '/manager/licenses/'
    | '/manager/providers/'
    | '/manager/users/'
    | '/api/dev/email/$template'
    | '/api/mobile/auth/activate'
    | '/api/mobile/auth/refresh'
    | '/api/mobile/auth/session'
    | '/api/mobile/manga-page/translate'
    | '/api/mobile/source-discovery/method-feedback'
    | '/api/mobile/source-discovery/plan'
    | '/api/mobile/source-discovery/verify'
    | '/api/mobile/subscription/cancel'
    | '/api/openapi/app/schema'
    | '/api/openapi/auth/schema'
    | '/manager/chapters/$cacheKey/'
    | '/manager/contacts/$id/'
    | '/manager/devices/$id/'
    | '/manager/jobs/$id/'
    | '/manager/licenses/$key/'
    | '/manager/users/$id/'
    | '/manager/users/new/'
    | '/api/mobile/jobs/$jobId/complete'
    | '/api/mobile/jobs/$jobId/result'
    | '/api/mobile/jobs/$jobId/'
    | '/manager/users/$id/update/'
    | '/api/mobile/jobs/$jobId/pages/$pageNumber'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRouteRoute: typeof AppRouteRouteWithChildren
  LoginRouteRoute: typeof LoginRouteRouteWithChildren
  ManagerRouteRoute: typeof ManagerRouteRouteWithChildren
  DownloadRoute: typeof DownloadRoute
  HowItWorksRoute: typeof HowItWorksRoute
  LogoutRoute: typeof LogoutRoute
  PricingRoute: typeof PricingRoute
  SupportRoute: typeof SupportRoute
  ApiContactRoute: typeof ApiContactRoute
  ApiUploadRoute: typeof ApiUploadRoute
  CheckoutTokenPackKeyRoute: typeof CheckoutTokenPackKeyRoute
  CheckoutCancelRoute: typeof CheckoutCancelRoute
  CheckoutSuccessRoute: typeof CheckoutSuccessRoute
  LegalPrivacyRoute: typeof LegalPrivacyRoute
  LegalTermsRoute: typeof LegalTermsRoute
  ApiActivationRedeemRoute: typeof ApiActivationRedeemRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
  ApiDownloadApkRoute: typeof ApiDownloadApkRoute
  ApiMobileHeartbeatRoute: typeof ApiMobileHeartbeatRoute
  ApiMobileJobsRoute: typeof ApiMobileJobsRouteWithChildren
  ApiOpenapiAppRoute: typeof ApiOpenapiAppRouteWithChildren
  ApiOpenapiAuthRoute: typeof ApiOpenapiAuthRouteWithChildren
  ApiPaymentsCheckoutRoute: typeof ApiPaymentsCheckoutRoute
  ApiPaymentsWebhookRoute: typeof ApiPaymentsWebhookRoute
  ApiRestSplatRoute: typeof ApiRestSplatRoute
  ApiRpcSplatRoute: typeof ApiRpcSplatRoute
  ApiDevEmailTemplateRoute: typeof ApiDevEmailTemplateRoute
  ApiMobileAuthActivateRoute: typeof ApiMobileAuthActivateRoute
  ApiMobileAuthRefreshRoute: typeof ApiMobileAuthRefreshRoute
  ApiMobileAuthSessionRoute: typeof ApiMobileAuthSessionRoute
  ApiMobileMangaPageTranslateRoute: typeof ApiMobileMangaPageTranslateRoute
  ApiMobileSourceDiscoveryMethodFeedbackRoute: typeof ApiMobileSourceDiscoveryMethodFeedbackRoute
  ApiMobileSourceDiscoveryPlanRoute: typeof ApiMobileSourceDiscoveryPlanRoute
  ApiMobileSourceDiscoveryVerifyRoute: typeof ApiMobileSourceDiscoveryVerifyRoute
  ApiMobileSubscriptionCancelRoute: typeof ApiMobileSubscriptionCancelRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/support': {
      id: '/support'
      path: '/support'
      fullPath: '/support'
      preLoaderRoute: typeof SupportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pricing': {
      id: '/pricing'
      path: '/pricing'
      fullPath: '/pricing'
      preLoaderRoute: typeof PricingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/logout': {
      id: '/logout'
      path: '/logout'
      fullPath: '/logout'
      preLoaderRoute: typeof LogoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/how-it-works': {
      id: '/how-it-works'
      path: '/how-it-works'
      fullPath: '/how-it-works'
      preLoaderRoute: typeof HowItWorksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/download': {
      id: '/download'
      path: '/download'
      fullPath: '/download'
      preLoaderRoute: typeof DownloadRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/manager': {
      id: '/manager'
      path: '/manager'
      fullPath: '/manager'
      preLoaderRoute: typeof ManagerRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/manager/': {
      id: '/manager/'
      path: '/'
      fullPath: '/manager/'
      preLoaderRoute: typeof ManagerIndexRouteImport
      parentRoute: typeof ManagerRouteRoute
    }
    '/login/': {
      id: '/login/'
      path: '/'
      fullPath: '/login/'
      preLoaderRoute: typeof LoginIndexRouteImport
      parentRoute: typeof LoginRouteRoute
    }
    '/app/': {
      id: '/app/'
      path: '/'
      fullPath: '/app/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/legal/terms': {
      id: '/legal/terms'
      path: '/legal/terms'
      fullPath: '/legal/terms'
      preLoaderRoute: typeof LegalTermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/legal/privacy': {
      id: '/legal/privacy'
      path: '/legal/privacy'
      fullPath: '/legal/privacy'
      preLoaderRoute: typeof LegalPrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkout/success': {
      id: '/checkout/success'
      path: '/checkout/success'
      fullPath: '/checkout/success'
      preLoaderRoute: typeof CheckoutSuccessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkout/cancel': {
      id: '/checkout/cancel'
      path: '/checkout/cancel'
      fullPath: '/checkout/cancel'
      preLoaderRoute: typeof CheckoutCancelRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkout/$tokenPackKey': {
      id: '/checkout/$tokenPackKey'
      path: '/checkout/$tokenPackKey'
      fullPath: '/checkout/$tokenPackKey'
      preLoaderRoute: typeof CheckoutTokenPackKeyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/upload': {
      id: '/api/upload'
      path: '/api/upload'
      fullPath: '/api/upload'
      preLoaderRoute: typeof ApiUploadRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/contact': {
      id: '/api/contact'
      path: '/api/contact'
      fullPath: '/api/contact'
      preLoaderRoute: typeof ApiContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/manager/users/': {
      id: '/manager/users/'
      path: '/users'
      fullPath: '/manager/users/'
      preLoaderRoute: typeof ManagerUsersIndexRouteImport
      parentRoute: typeof ManagerRouteRoute
    }
    '/manager/providers/': {
      id: '/manager/providers/'
      path: '/providers'
      fullPath: '/manager/providers/'
      preLoaderRoute: typeof ManagerProvidersIndexRouteImport
      parentRoute: typeof ManagerRouteRoute
    }
    '/manager/licenses/': {
      id: '/manager/licenses/'
      path: '/licenses'
      fullPath: '/manager/licenses/'
      preLoaderRoute: typeof ManagerLicensesIndexRouteImport
      parentRoute: typeof ManagerRouteRoute
    }
    '/manager/jobs/': {
      id: '/manager/jobs/'
      path: '/jobs'
      fullPath: '/manager/jobs/'
      preLoaderRoute: typeof ManagerJobsIndexRouteImport
      parentRoute: typeof ManagerRouteRoute
    }
    '/manager/dashboard/': {
      id: '/manager/dashboard/'
      path: '/dashboard'
      fullPath: '/manager/dashboard/'
      preLoaderRoute: typeof ManagerDashboardIndexRouteImport
      parentRoute: typeof ManagerRouteRoute
    }
    '/manager/contacts/': {
      id: '/manager/contacts/'
      path: '/contacts'
      fullPath: '/manager/contacts/'
      preLoaderRoute: typeof ManagerContactsIndexRouteImport
      parentRoute: typeof ManagerRouteRoute
    }
    '/manager/chapters/': {
      id: '/manager/chapters/'
      path: '/chapters'
      fullPath: '/manager/chapters/'
      preLoaderRoute: typeof ManagerChaptersIndexRouteImport
      parentRoute: typeof ManagerRouteRoute
    }
    '/manager/account/': {
      id: '/manager/account/'
      path: '/account'
      fullPath: '/manager/account/'
      preLoaderRoute: typeof ManagerAccountIndexRouteImport
      parentRoute: typeof ManagerRouteRoute
    }
    '/login/verify/': {
      id: '/login/verify/'
      path: '/verify'
      fullPath: '/login/verify/'
      preLoaderRoute: typeof LoginVerifyIndexRouteImport
      parentRoute: typeof LoginRouteRoute
    }
    '/login/error/': {
      id: '/login/error/'
      path: '/error'
      fullPath: '/login/error/'
      preLoaderRoute: typeof LoginErrorIndexRouteImport
      parentRoute: typeof LoginRouteRoute
    }
    '/app/account/': {
      id: '/app/account/'
      path: '/account'
      fullPath: '/app/account/'
      preLoaderRoute: typeof AppAccountIndexRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/api/rpc/$': {
      id: '/api/rpc/$'
      path: '/api/rpc/$'
      fullPath: '/api/rpc/$'
      preLoaderRoute: typeof ApiRpcSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/rest/$': {
      id: '/api/rest/$'
      path: '/api/rest/$'
      fullPath: '/api/rest/$'
      preLoaderRoute: typeof ApiRestSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/payments/webhook': {
      id: '/api/payments/webhook'
      path: '/api/payments/webhook'
      fullPath: '/api/payments/webhook'
      preLoaderRoute: typeof ApiPaymentsWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/payments/checkout': {
      id: '/api/payments/checkout'
      path: '/api/payments/checkout'
      fullPath: '/api/payments/checkout'
      preLoaderRoute: typeof ApiPaymentsCheckoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/openapi/auth': {
      id: '/api/openapi/auth'
      path: '/api/openapi/auth'
      fullPath: '/api/openapi/auth'
      preLoaderRoute: typeof ApiOpenapiAuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/openapi/app': {
      id: '/api/openapi/app'
      path: '/api/openapi/app'
      fullPath: '/api/openapi/app'
      preLoaderRoute: typeof ApiOpenapiAppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/mobile/jobs': {
      id: '/api/mobile/jobs'
      path: '/api/mobile/jobs'
      fullPath: '/api/mobile/jobs'
      preLoaderRoute: typeof ApiMobileJobsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/mobile/heartbeat': {
      id: '/api/mobile/heartbeat'
      path: '/api/mobile/heartbeat'
      fullPath: '/api/mobile/heartbeat'
      preLoaderRoute: typeof ApiMobileHeartbeatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/download/apk': {
      id: '/api/download/apk'
      path: '/api/download/apk'
      fullPath: '/api/download/apk'
      preLoaderRoute: typeof ApiDownloadApkRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/activation/redeem': {
      id: '/api/activation/redeem'
      path: '/api/activation/redeem'
      fullPath: '/api/activation/redeem'
      preLoaderRoute: typeof ApiActivationRedeemRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/manager/users/new/': {
      id: '/manager/users/new/'
      path: '/users/new'
      fullPath: '/manager/users/new/'
      preLoaderRoute: typeof ManagerUsersNewIndexRouteImport
      parentRoute: typeof ManagerRouteRoute
    }
    '/manager/users/$id/': {
      id: '/manager/users/$id/'
      path: '/users/$id'
      fullPath: '/manager/users/$id/'
      preLoaderRoute: typeof ManagerUsersIdIndexRouteImport
      parentRoute: typeof ManagerRouteRoute
    }
    '/manager/licenses/$key/': {
      id: '/manager/licenses/$key/'
      path: '/licenses/$key'
      fullPath: '/manager/licenses/$key/'
      preLoaderRoute: typeof ManagerLicensesKeyIndexRouteImport
      parentRoute: typeof ManagerRouteRoute
    }
    '/manager/jobs/$id/': {
      id: '/manager/jobs/$id/'
      path: '/jobs/$id'
      fullPath: '/manager/jobs/$id/'
      preLoaderRoute: typeof ManagerJobsIdIndexRouteImport
      parentRoute: typeof ManagerRouteRoute
    }
    '/manager/devices/$id/': {
      id: '/manager/devices/$id/'
      path: '/devices/$id'
      fullPath: '/manager/devices/$id/'
      preLoaderRoute: typeof ManagerDevicesIdIndexRouteImport
      parentRoute: typeof ManagerRouteRoute
    }
    '/manager/contacts/$id/': {
      id: '/manager/contacts/$id/'
      path: '/contacts/$id'
      fullPath: '/manager/contacts/$id/'
      preLoaderRoute: typeof ManagerContactsIdIndexRouteImport
      parentRoute: typeof ManagerRouteRoute
    }
    '/manager/chapters/$cacheKey/': {
      id: '/manager/chapters/$cacheKey/'
      path: '/chapters/$cacheKey'
      fullPath: '/manager/chapters/$cacheKey/'
      preLoaderRoute: typeof ManagerChaptersCacheKeyIndexRouteImport
      parentRoute: typeof ManagerRouteRoute
    }
    '/api/openapi/auth/schema': {
      id: '/api/openapi/auth/schema'
      path: '/schema'
      fullPath: '/api/openapi/auth/schema'
      preLoaderRoute: typeof ApiOpenapiAuthSchemaRouteImport
      parentRoute: typeof ApiOpenapiAuthRoute
    }
    '/api/openapi/app/schema': {
      id: '/api/openapi/app/schema'
      path: '/schema'
      fullPath: '/api/openapi/app/schema'
      preLoaderRoute: typeof ApiOpenapiAppSchemaRouteImport
      parentRoute: typeof ApiOpenapiAppRoute
    }
    '/api/mobile/subscription/cancel': {
      id: '/api/mobile/subscription/cancel'
      path: '/api/mobile/subscription/cancel'
      fullPath: '/api/mobile/subscription/cancel'
      preLoaderRoute: typeof ApiMobileSubscriptionCancelRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/mobile/source-discovery/verify': {
      id: '/api/mobile/source-discovery/verify'
      path: '/api/mobile/source-discovery/verify'
      fullPath: '/api/mobile/source-discovery/verify'
      preLoaderRoute: typeof ApiMobileSourceDiscoveryVerifyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/mobile/source-discovery/method-feedback': {
      id: '/api/mobile/source-discovery/method-feedback'
      path: '/api/mobile/source-discovery/method-feedback'
      fullPath: '/api/mobile/source-discovery/method-feedback'
      preLoaderRoute: typeof ApiMobileSourceDiscoveryMethodFeedbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/mobile/source-discovery/plan': {
      id: '/api/mobile/source-discovery/plan'
      path: '/api/mobile/source-discovery/plan'
      fullPath: '/api/mobile/source-discovery/plan'
      preLoaderRoute: typeof ApiMobileSourceDiscoveryPlanRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/mobile/manga-page/translate': {
      id: '/api/mobile/manga-page/translate'
      path: '/api/mobile/manga-page/translate'
      fullPath: '/api/mobile/manga-page/translate'
      preLoaderRoute: typeof ApiMobileMangaPageTranslateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/mobile/auth/session': {
      id: '/api/mobile/auth/session'
      path: '/api/mobile/auth/session'
      fullPath: '/api/mobile/auth/session'
      preLoaderRoute: typeof ApiMobileAuthSessionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/mobile/auth/refresh': {
      id: '/api/mobile/auth/refresh'
      path: '/api/mobile/auth/refresh'
      fullPath: '/api/mobile/auth/refresh'
      preLoaderRoute: typeof ApiMobileAuthRefreshRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/mobile/auth/activate': {
      id: '/api/mobile/auth/activate'
      path: '/api/mobile/auth/activate'
      fullPath: '/api/mobile/auth/activate'
      preLoaderRoute: typeof ApiMobileAuthActivateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/dev/email/$template': {
      id: '/api/dev/email/$template'
      path: '/api/dev/email/$template'
      fullPath: '/api/dev/email/$template'
      preLoaderRoute: typeof ApiDevEmailTemplateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/manager/users/$id/update/': {
      id: '/manager/users/$id/update/'
      path: '/users/$id/update'
      fullPath: '/manager/users/$id/update/'
      preLoaderRoute: typeof ManagerUsersIdUpdateIndexRouteImport
      parentRoute: typeof ManagerRouteRoute
    }
    '/api/mobile/jobs/$jobId/': {
      id: '/api/mobile/jobs/$jobId/'
      path: '/$jobId'
      fullPath: '/api/mobile/jobs/$jobId/'
      preLoaderRoute: typeof ApiMobileJobsJobIdIndexRouteImport
      parentRoute: typeof ApiMobileJobsRoute
    }
    '/api/mobile/jobs/$jobId/result': {
      id: '/api/mobile/jobs/$jobId/result'
      path: '/$jobId/result'
      fullPath: '/api/mobile/jobs/$jobId/result'
      preLoaderRoute: typeof ApiMobileJobsJobIdResultRouteImport
      parentRoute: typeof ApiMobileJobsRoute
    }
    '/api/mobile/jobs/$jobId/complete': {
      id: '/api/mobile/jobs/$jobId/complete'
      path: '/$jobId/complete'
      fullPath: '/api/mobile/jobs/$jobId/complete'
      preLoaderRoute: typeof ApiMobileJobsJobIdCompleteRouteImport
      parentRoute: typeof ApiMobileJobsRoute
    }
    '/api/mobile/jobs/$jobId/pages/$pageNumber': {
      id: '/api/mobile/jobs/$jobId/pages/$pageNumber'
      path: '/$jobId/pages/$pageNumber'
      fullPath: '/api/mobile/jobs/$jobId/pages/$pageNumber'
      preLoaderRoute: typeof ApiMobileJobsJobIdPagesPageNumberRouteImport
      parentRoute: typeof ApiMobileJobsRoute
    }
  }
}

interface AppRouteRouteChildren {
  AppIndexRoute: typeof AppIndexRoute
  AppAccountIndexRoute: typeof AppAccountIndexRoute
}

const AppRouteRouteChildren: AppRouteRouteChildren = {
  AppIndexRoute: AppIndexRoute,
  AppAccountIndexRoute: AppAccountIndexRoute,
}

const AppRouteRouteWithChildren = AppRouteRoute._addFileChildren(
  AppRouteRouteChildren,
)

interface LoginRouteRouteChildren {
  LoginIndexRoute: typeof LoginIndexRoute
  LoginErrorIndexRoute: typeof LoginErrorIndexRoute
  LoginVerifyIndexRoute: typeof LoginVerifyIndexRoute
}

const LoginRouteRouteChildren: LoginRouteRouteChildren = {
  LoginIndexRoute: LoginIndexRoute,
  LoginErrorIndexRoute: LoginErrorIndexRoute,
  LoginVerifyIndexRoute: LoginVerifyIndexRoute,
}

const LoginRouteRouteWithChildren = LoginRouteRoute._addFileChildren(
  LoginRouteRouteChildren,
)

interface ManagerRouteRouteChildren {
  ManagerIndexRoute: typeof ManagerIndexRoute
  ManagerAccountIndexRoute: typeof ManagerAccountIndexRoute
  ManagerChaptersIndexRoute: typeof ManagerChaptersIndexRoute
  ManagerContactsIndexRoute: typeof ManagerContactsIndexRoute
  ManagerDashboardIndexRoute: typeof ManagerDashboardIndexRoute
  ManagerJobsIndexRoute: typeof ManagerJobsIndexRoute
  ManagerLicensesIndexRoute: typeof ManagerLicensesIndexRoute
  ManagerProvidersIndexRoute: typeof ManagerProvidersIndexRoute
  ManagerUsersIndexRoute: typeof ManagerUsersIndexRoute
  ManagerChaptersCacheKeyIndexRoute: typeof ManagerChaptersCacheKeyIndexRoute
  ManagerContactsIdIndexRoute: typeof ManagerContactsIdIndexRoute
  ManagerDevicesIdIndexRoute: typeof ManagerDevicesIdIndexRoute
  ManagerJobsIdIndexRoute: typeof ManagerJobsIdIndexRoute
  ManagerLicensesKeyIndexRoute: typeof ManagerLicensesKeyIndexRoute
  ManagerUsersIdIndexRoute: typeof ManagerUsersIdIndexRoute
  ManagerUsersNewIndexRoute: typeof ManagerUsersNewIndexRoute
  ManagerUsersIdUpdateIndexRoute: typeof ManagerUsersIdUpdateIndexRoute
}

const ManagerRouteRouteChildren: ManagerRouteRouteChildren = {
  ManagerIndexRoute: ManagerIndexRoute,
  ManagerAccountIndexRoute: ManagerAccountIndexRoute,
  ManagerChaptersIndexRoute: ManagerChaptersIndexRoute,
  ManagerContactsIndexRoute: ManagerContactsIndexRoute,
  ManagerDashboardIndexRoute: ManagerDashboardIndexRoute,
  ManagerJobsIndexRoute: ManagerJobsIndexRoute,
  ManagerLicensesIndexRoute: ManagerLicensesIndexRoute,
  ManagerProvidersIndexRoute: ManagerProvidersIndexRoute,
  ManagerUsersIndexRoute: ManagerUsersIndexRoute,
  ManagerChaptersCacheKeyIndexRoute: ManagerChaptersCacheKeyIndexRoute,
  ManagerContactsIdIndexRoute: ManagerContactsIdIndexRoute,
  ManagerDevicesIdIndexRoute: ManagerDevicesIdIndexRoute,
  ManagerJobsIdIndexRoute: ManagerJobsIdIndexRoute,
  ManagerLicensesKeyIndexRoute: ManagerLicensesKeyIndexRoute,
  ManagerUsersIdIndexRoute: ManagerUsersIdIndexRoute,
  ManagerUsersNewIndexRoute: ManagerUsersNewIndexRoute,
  ManagerUsersIdUpdateIndexRoute: ManagerUsersIdUpdateIndexRoute,
}

const ManagerRouteRouteWithChildren = ManagerRouteRoute._addFileChildren(
  ManagerRouteRouteChildren,
)

interface ApiMobileJobsRouteChildren {
  ApiMobileJobsJobIdCompleteRoute: typeof ApiMobileJobsJobIdCompleteRoute
  ApiMobileJobsJobIdResultRoute: typeof ApiMobileJobsJobIdResultRoute
  ApiMobileJobsJobIdIndexRoute: typeof ApiMobileJobsJobIdIndexRoute
  ApiMobileJobsJobIdPagesPageNumberRoute: typeof ApiMobileJobsJobIdPagesPageNumberRoute
}

const ApiMobileJobsRouteChildren: ApiMobileJobsRouteChildren = {
  ApiMobileJobsJobIdCompleteRoute: ApiMobileJobsJobIdCompleteRoute,
  ApiMobileJobsJobIdResultRoute: ApiMobileJobsJobIdResultRoute,
  ApiMobileJobsJobIdIndexRoute: ApiMobileJobsJobIdIndexRoute,
  ApiMobileJobsJobIdPagesPageNumberRoute:
    ApiMobileJobsJobIdPagesPageNumberRoute,
}

const ApiMobileJobsRouteWithChildren = ApiMobileJobsRoute._addFileChildren(
  ApiMobileJobsRouteChildren,
)

interface ApiOpenapiAppRouteChildren {
  ApiOpenapiAppSchemaRoute: typeof ApiOpenapiAppSchemaRoute
}

const ApiOpenapiAppRouteChildren: ApiOpenapiAppRouteChildren = {
  ApiOpenapiAppSchemaRoute: ApiOpenapiAppSchemaRoute,
}

const ApiOpenapiAppRouteWithChildren = ApiOpenapiAppRoute._addFileChildren(
  ApiOpenapiAppRouteChildren,
)

interface ApiOpenapiAuthRouteChildren {
  ApiOpenapiAuthSchemaRoute: typeof ApiOpenapiAuthSchemaRoute
}

const ApiOpenapiAuthRouteChildren: ApiOpenapiAuthRouteChildren = {
  ApiOpenapiAuthSchemaRoute: ApiOpenapiAuthSchemaRoute,
}

const ApiOpenapiAuthRouteWithChildren = ApiOpenapiAuthRoute._addFileChildren(
  ApiOpenapiAuthRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRouteRoute: AppRouteRouteWithChildren,
  LoginRouteRoute: LoginRouteRouteWithChildren,
  ManagerRouteRoute: ManagerRouteRouteWithChildren,
  DownloadRoute: DownloadRoute,
  HowItWorksRoute: HowItWorksRoute,
  LogoutRoute: LogoutRoute,
  PricingRoute: PricingRoute,
  SupportRoute: SupportRoute,
  ApiContactRoute: ApiContactRoute,
  ApiUploadRoute: ApiUploadRoute,
  CheckoutTokenPackKeyRoute: CheckoutTokenPackKeyRoute,
  CheckoutCancelRoute: CheckoutCancelRoute,
  CheckoutSuccessRoute: CheckoutSuccessRoute,
  LegalPrivacyRoute: LegalPrivacyRoute,
  LegalTermsRoute: LegalTermsRoute,
  ApiActivationRedeemRoute: ApiActivationRedeemRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
  ApiDownloadApkRoute: ApiDownloadApkRoute,
  ApiMobileHeartbeatRoute: ApiMobileHeartbeatRoute,
  ApiMobileJobsRoute: ApiMobileJobsRouteWithChildren,
  ApiOpenapiAppRoute: ApiOpenapiAppRouteWithChildren,
  ApiOpenapiAuthRoute: ApiOpenapiAuthRouteWithChildren,
  ApiPaymentsCheckoutRoute: ApiPaymentsCheckoutRoute,
  ApiPaymentsWebhookRoute: ApiPaymentsWebhookRoute,
  ApiRestSplatRoute: ApiRestSplatRoute,
  ApiRpcSplatRoute: ApiRpcSplatRoute,
  ApiDevEmailTemplateRoute: ApiDevEmailTemplateRoute,
  ApiMobileAuthActivateRoute: ApiMobileAuthActivateRoute,
  ApiMobileAuthRefreshRoute: ApiMobileAuthRefreshRoute,
  ApiMobileAuthSessionRoute: ApiMobileAuthSessionRoute,
  ApiMobileMangaPageTranslateRoute: ApiMobileMangaPageTranslateRoute,
  ApiMobileSourceDiscoveryMethodFeedbackRoute:
    ApiMobileSourceDiscoveryMethodFeedbackRoute,
  ApiMobileSourceDiscoveryPlanRoute: ApiMobileSourceDiscoveryPlanRoute,
  ApiMobileSourceDiscoveryVerifyRoute: ApiMobileSourceDiscoveryVerifyRoute,
  ApiMobileSubscriptionCancelRoute: ApiMobileSubscriptionCancelRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
